package com.utp.jhs4.entity;
// Generated 18/09/2019 12:46:49 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private BigDecimal isbn;
     private String titulo;
     private String autor;
     //private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);

    public Libros() {
    }

	
    public Libros(BigDecimal isbn, String titulo, String autor) {
        this.isbn = isbn;
        this.titulo = titulo;
        this.autor = autor;
    }
    public Libros(BigDecimal isbn, String titulo, String autor, Set<Prestamos> prestamoses) {
       this.isbn = isbn;
       this.titulo = titulo;
       this.autor = autor;
       //this.prestamoses = prestamoses;
    }
   
    public BigDecimal getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(BigDecimal isbn) {
        this.isbn = isbn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    /*public Set<Prestamos> getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set<Prestamos> prestamoses) {
        this.prestamoses = prestamoses;
    }*/




}


