package com.utp.jhs4.entity;
// Generated 18/09/2019 12:46:49 PM by Hibernate Tools 4.3.1



/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private PrestamosId id;
     private Libros libros;
     private Ciudadanos ciudadanos;

    public Prestamos() {
    }

    public Prestamos(PrestamosId id, Libros libros, Ciudadanos ciudadanos) {
       this.id = id;
       this.libros = libros;
       this.ciudadanos = ciudadanos;
    }
   
    public PrestamosId getId() {
        return this.id;
    }
    
    public void setId(PrestamosId id) {
        this.id = id;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public Ciudadanos getCiudadanos() {
        return this.ciudadanos;
    }
    
    public void setCiudadanos(Ciudadanos ciudadanos) {
        this.ciudadanos = ciudadanos;
    }




}


