package com.utp.jhs4.entity;
// Generated 18/09/2019 12:46:49 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PrestamosId generated by hbm2java
 */
public class PrestamosId  implements java.io.Serializable {


     private BigDecimal isbnFk;
     private BigDecimal cedulaFk;

    public PrestamosId() {
    }

    public PrestamosId(BigDecimal isbnFk, BigDecimal cedulaFk) {
       this.isbnFk = isbnFk;
       this.cedulaFk = cedulaFk;
    }
   
    public BigDecimal getIsbnFk() {
        return this.isbnFk;
    }
    
    public void setIsbnFk(BigDecimal isbnFk) {
        this.isbnFk = isbnFk;
    }
    public BigDecimal getCedulaFk() {
        return this.cedulaFk;
    }
    
    public void setCedulaFk(BigDecimal cedulaFk) {
        this.cedulaFk = cedulaFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrestamosId) ) return false;
		 PrestamosId castOther = ( PrestamosId ) other; 
         
		 return ( (this.getIsbnFk()==castOther.getIsbnFk()) || ( this.getIsbnFk()!=null && castOther.getIsbnFk()!=null && this.getIsbnFk().equals(castOther.getIsbnFk()) ) )
 && ( (this.getCedulaFk()==castOther.getCedulaFk()) || ( this.getCedulaFk()!=null && castOther.getCedulaFk()!=null && this.getCedulaFk().equals(castOther.getCedulaFk()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIsbnFk() == null ? 0 : this.getIsbnFk().hashCode() );
         result = 37 * result + ( getCedulaFk() == null ? 0 : this.getCedulaFk().hashCode() );
         return result;
   }   


}


